"""empty message

Revision ID: 102c45d8ca07
Revises: 52ef3bb09133
Create Date: 2025-09-26 20:05:11.227841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '102c45d8ca07'
down_revision = '52ef3bb09133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_success', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('result', sa.JSON(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_column('email')

    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.drop_column('result')
        batch_op.drop_column('is_success')

    # ### end Alembic commands ###
