"""Add senator_people table

Revision ID: 1ab36f2d4ea3
Revises: 3ae44e542e23
Create Date: 2025-10-06 08:04:55.479708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ab36f2d4ea3'
down_revision = '3ae44e542e23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('senator_people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salutation', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('organization', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=128), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('business_phone', sa.String(length=64), nullable=True),
    sa.Column('mobile_phone', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('sector', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('senator_people', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_senator_people_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_senator_people_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_senator_people_organization'), ['organization'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('senator_people', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_senator_people_organization'))
        batch_op.drop_index(batch_op.f('ix_senator_people_last_name'))
        batch_op.drop_index(batch_op.f('ix_senator_people_first_name'))

    op.drop_table('senator_people')
    # ### end Alembic commands ###
