"""empty message

Revision ID: 345a4ca4756c
Revises: 77923ab5cb42
Create Date: 2025-08-27 23:34:53.241251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '345a4ca4756c'
down_revision = '77923ab5cb42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salutation', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('organization', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=128), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('business_phone', sa.String(length=64), nullable=True),
    sa.Column('mobile_phone', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('sector', sa.String(length=64), nullable=True),
    sa.Column('linkedin', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_people_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_people_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_people_organization'), ['organization'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_people_organization'))
        batch_op.drop_index(batch_op.f('ix_people_last_name'))
        batch_op.drop_index(batch_op.f('ix_people_first_name'))

    op.drop_table('people')
    # ### end Alembic commands ###
