"""empty message

Revision ID: 4cb766acd733
Revises: 52ef3bb09133
Create Date: 2025-09-27 12:45:12.346961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cb766acd733'
down_revision = '52ef3bb09133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('is_expired', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('scrape_outcome_1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salutation', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('organization', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=128), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('business_phone', sa.String(length=64), nullable=True),
    sa.Column('mobile_phone', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('sector', sa.String(length=64), nullable=True),
    sa.Column('linkedin', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scrape_outcome_1', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scrape_outcome_1_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_scrape_outcome_1_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_scrape_outcome_1_organization'), ['organization'], unique=False)

    op.create_table('scrape_outcome_2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salutation', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('organization', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=128), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('business_phone', sa.String(length=64), nullable=True),
    sa.Column('mobile_phone', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('sector', sa.String(length=64), nullable=True),
    sa.Column('linkedin', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scrape_outcome_2', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scrape_outcome_2_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_scrape_outcome_2_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_scrape_outcome_2_organization'), ['organization'], unique=False)

    op.create_table('scrape_outcome_3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salutation', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('organization', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=128), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('business_phone', sa.String(length=64), nullable=True),
    sa.Column('mobile_phone', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('sector', sa.String(length=64), nullable=True),
    sa.Column('linkedin', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scrape_outcome_3', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scrape_outcome_3_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_scrape_outcome_3_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_scrape_outcome_3_organization'), ['organization'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrape_outcome_3', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scrape_outcome_3_organization'))
        batch_op.drop_index(batch_op.f('ix_scrape_outcome_3_last_name'))
        batch_op.drop_index(batch_op.f('ix_scrape_outcome_3_first_name'))

    op.drop_table('scrape_outcome_3')
    with op.batch_alter_table('scrape_outcome_2', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scrape_outcome_2_organization'))
        batch_op.drop_index(batch_op.f('ix_scrape_outcome_2_last_name'))
        batch_op.drop_index(batch_op.f('ix_scrape_outcome_2_first_name'))

    op.drop_table('scrape_outcome_2')
    with op.batch_alter_table('scrape_outcome_1', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scrape_outcome_1_organization'))
        batch_op.drop_index(batch_op.f('ix_scrape_outcome_1_last_name'))
        batch_op.drop_index(batch_op.f('ix_scrape_outcome_1_first_name'))

    op.drop_table('scrape_outcome_1')
    op.drop_table('profile')
    op.drop_table('ip')
    # ### end Alembic commands ###
