"""empty message

Revision ID: 52ef3bb09133
Revises: 345a4ca4756c
Create Date: 2025-08-29 23:19:28.363065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52ef3bb09133'
down_revision = '345a4ca4756c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=True),
    sa.Column('record_name', sa.String(length=64), nullable=True),
    sa.Column('error', sa.String(length=256), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['log_id'], ['log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_detail')
    op.drop_table('log')
    # ### end Alembic commands ###
