"""empty message

Revision ID: 8ed7a0336279
Revises: 1ab36f2d4ea3
Create Date: 2025-10-06 10:21:20.736968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ed7a0336279'
down_revision = '1ab36f2d4ea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('senator_people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_url', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('senator_people', schema=None) as batch_op:
        batch_op.drop_column('profile_url')

    # ### end Alembic commands ###
