"""empty message

Revision ID: fe4e3d81e0eb
Revises: 2714fa875dda
Create Date: 2025-09-27 21:24:17.582563

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'fe4e3d81e0eb'
down_revision = '2714fa875dda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('result',
               existing_type=sqlite.JSON(),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.drop_column('create_at')
        batch_op.drop_column('is_success')

    with op.batch_alter_table('log_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('detail', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('log_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('error')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('error', sa.VARCHAR(length=256), nullable=True))
        batch_op.alter_column('log_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('detail')
        batch_op.drop_column('status')

    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_success', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('create_at', sa.DATETIME(), nullable=True))
        batch_op.alter_column('result',
               existing_type=sa.String(length=128),
               type_=sqlite.JSON(),
               existing_nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
